import { ContactModel, ContactModelPagedResult } from '@reapit/foundations-ts-definitions'

export const mockContactModelPagedResult: ContactModelPagedResult = {
  _embedded: [
    {
      id: 'MKT23007375',
      created: '2023-03-17T10:35:18Z',
      modified: '2023-03-20T09:39:02Z',
      title: 'Mr',
      forename: 'Foo',
      surname: 'Bar',
      dateOfBirth: '2023-03-08',
      active: true,
      marketingConsent: 'grant',
      identityCheck: 'unchecked',
      source: {
        id: 'SRC157',
        type: 'source',
      },
      homePhone: '234234234',
      workPhone: '2342342344',
      mobilePhone: '242423424',
      email: 'foo@bar.com',
      fromArchive: false,
      primaryAddress: {
        type: 'primary',
        buildingName: 'Foo',
        buildingNumber: 'Bar',
        line1: 'Foo',
        line2: 'Bar',
        line3: 'Foo',
        line4: 'Bar',
        postcode: 'Foo',
        countryId: 'GB',
      },
      secondaryAddress: {
        type: 'primary',
        buildingName: 'Foo',
        buildingNumber: 'Bar',
        line1: 'Foo',
        line2: 'Bar',
        line3: 'Foo',
        line4: 'Bar',
        postcode: 'Foo',
        countryId: 'GB',
      },
      workAddress: {
        type: 'primary',
        buildingName: 'Foo',
        buildingNumber: 'Bar',
        line1: 'Foo',
        line2: 'Bar',
        line3: 'Foo',
        line4: 'Bar',
        postcode: 'Foo',
        countryId: 'GB',
      },
      officeIds: ['LEA'],
      negotiatorIds: ['MRLN'],
      categoryIds: ['XLY'],
      communicationPreferenceLetter: true,
      communicationPreferenceEmail: true,
      communicationPreferencePhone: true,
      communicationPreferenceSMS: true,
      additionalContactDetails: [],
      _eTag: '"997FDB9A176B6E8E07927EBA27E1A8F6"',
      _links: {
        self: {
          href: '/contacts/MKT23007375',
        },
        documents: {
          href: '/documents/?associatedType=contact&associatedId=MKT23007375',
        },
        identityChecks: {
          href: '/identityChecks/?contactId=MKT23007375',
        },
        offices: {
          href: '/offices/?id=LEA',
        },
        negotiators: {
          href: '/negotiators/?id=MRLN',
        },
        categories: {
          href: '/configuration/contactCategories/?id=XLY',
        },
        relationships: {
          href: '/contacts/MKT23007375/relationships',
        },
        subscriptions: {
          href: '/contacts/MKT23007375/subscriptions',
        },
        source: {
          href: '/sources/SRC157',
        },
      },
      metadata: {},
    },
    {
      id: 'MKT23007374',
      created: '2023-03-17T10:33:59Z',
      modified: '2023-03-20T09:39:28Z',
      title: 'Mr',
      forename: 'Foo',
      surname: 'Bar',
      dateOfBirth: '2023-03-08',
      active: false,
      marketingConsent: 'grant',
      identityCheck: 'unchecked',
      source: {
        id: 'SRC157',
        type: 'source',
      },
      homePhone: '234234234',
      workPhone: '2342342344',
      mobilePhone: '242423424',
      email: 'foo@bar.com',
      fromArchive: false,
      primaryAddress: {
        type: 'primary',
        buildingName: 'Foo',
        buildingNumber: 'Bar',
        line1: 'Foo',
        line2: 'Bar',
        line3: 'Foo',
        line4: 'Bar',
        postcode: 'Foo',
        countryId: 'GB',
      },
      secondaryAddress: {
        type: 'secondary',
        buildingName: 'Foo',
        buildingNumber: 'Bar',
        line1: 'Foo',
        line2: 'Bar',
        line3: 'Foo',
        line4: 'Bar',
        postcode: 'Foo',
        countryId: 'GB',
      },
      workAddress: {
        type: 'work',
        buildingName: 'Foo',
        buildingNumber: 'Bar',
        line1: 'Foo',
        line2: 'Bar',
        line3: 'Foo',
        line4: 'Bar',
        postcode: 'Foo',
        countryId: 'GB',
      },
      officeIds: ['LEA'],
      negotiatorIds: ['MRLN'],
      categoryIds: ['XLY'],
      communicationPreferenceLetter: true,
      communicationPreferenceEmail: true,
      communicationPreferencePhone: true,
      communicationPreferenceSMS: true,
      additionalContactDetails: [],
      _eTag: '"9A61974D882B5838D2C8F434DDAE383F"',
      _links: {
        self: {
          href: '/contacts/MKT23007374',
        },
        documents: {
          href: '/documents/?associatedType=contact&associatedId=MKT23007374',
        },
        identityChecks: {
          href: '/identityChecks/?contactId=MKT23007374',
        },
        offices: {
          href: '/offices/?id=LEA',
        },
        negotiators: {
          href: '/negotiators/?id=MRLN',
        },
        categories: {
          href: '/configuration/contactCategories/?id=XLY',
        },
        relationships: {
          href: '/contacts/MKT23007374/relationships',
        },
        subscriptions: {
          href: '/contacts/MKT23007374/subscriptions',
        },
        source: {
          href: '/sources/SRC157',
        },
      },
      metadata: {},
    },
  ],
  pageNumber: 1,
  pageSize: 12,
  pageCount: 2,
  totalPageCount: 1,
  totalCount: 2,
  _links: {
    self: {
      href: '/contacts/?PageNumber=1&PageSize=12&name=foo bar',
    },
    first: {
      href: '/contacts/?PageNumber=1&PageSize=12&name=foo bar',
    },
  },
}

export const mockContactModel: ContactModel = {
  id: 'MKT23007375',
  created: '2023-03-17T10:35:18Z',
  modified: '2023-03-20T09:39:02Z',
  title: 'Mr',
  forename: 'Foo',
  surname: 'Bar',
  dateOfBirth: '2023-03-08',
  active: true,
  marketingConsent: 'grant',
  identityCheck: 'unchecked',
  source: {
    id: 'SRC157',
    type: 'source',
  },
  homePhone: '234234234',
  workPhone: '2342342344',
  mobilePhone: '242423424',
  email: 'foo@bar.com',
  fromArchive: false,
  primaryAddress: {
    type: 'primary',
    buildingName: 'Foo',
    buildingNumber: 'Bar',
    line1: 'Foo',
    line2: 'Bar',
    line3: 'Foo',
    line4: 'Bar',
    postcode: 'Foo',
    countryId: 'GB',
  },
  secondaryAddress: {
    type: 'primary',
    buildingName: 'Foo',
    buildingNumber: 'Bar',
    line1: 'Foo',
    line2: 'Bar',
    line3: 'Foo',
    line4: 'Bar',
    postcode: 'Foo',
    countryId: 'GB',
  },
  workAddress: {
    type: 'primary',
    buildingName: 'Foo',
    buildingNumber: 'Bar',
    line1: 'Foo',
    line2: 'Bar',
    line3: 'Foo',
    line4: 'Bar',
    postcode: 'Foo',
    countryId: 'GB',
  },
  officeIds: ['LEA'],
  negotiatorIds: ['MRLN'],
  categoryIds: ['XLY'],
  communicationPreferenceLetter: true,
  communicationPreferenceEmail: true,
  communicationPreferencePhone: true,
  communicationPreferenceSMS: true,
  _eTag: '"997FDB9A176B6E8E07927EBA27E1A8F6"',
  _links: {
    self: {
      href: '/contacts/MKT23007375',
    },
    documents: {
      href: '/documents/?associatedType=contact&associatedId=MKT23007375',
    },
    identityChecks: {
      href: '/identityChecks/?contactId=MKT23007375',
    },
    offices: {
      href: '/offices/?id=LEA',
    },
    negotiators: {
      href: '/negotiators/?id=MRLN',
    },
    categories: {
      href: '/configuration/contactCategories/?id=XLY',
    },
    relationships: {
      href: '/contacts/MKT23007375/relationships',
    },
    subscriptions: {
      href: '/contacts/MKT23007375/subscriptions',
    },
    source: {
      href: '/sources/SRC157',
    },
  },
  metadata: {},
  _embedded: {
    negotiators: [
      {
        id: 'MRLN',
        created: '2021-10-31T15:12:46Z',
        modified: '2021-10-31T15:12:46Z',
        name: 'Mr Alfred Williamson',
        jobTitle: 'LL EA Sales Negotiator',
        officeId: 'TLE',
        workPhone: '01234 224466',
        mobilePhone: '07890 887755',
        email: 'a.williamson@email.com',
        profileImageUrl: null,
        active: true,
        metadata: null,
        _eTag: '"93E3A22E2258AD53312B8AE4E28C851E"',
        _links: {
          self: {
            href: '/negotiators/MRLN',
          },
          office: {
            href: '/offices/TLE',
          },
        },
        _embedded: null,
      },
    ],
    offices: [
      {
        id: 'LEA',
        created: '2021-02-11T15:20:15Z',
        modified: '2021-02-11T15:20:15Z',
        name: 'London Estate Agent',
        manager: 'Mr John Smith',
        active: true,
        address: {
          buildingName: '257',
          buildingNumber: '15',
          line1: 'Example street',
          line2: 'Solihull',
          line3: 'West Midlands',
          line4: '',
          postcode: 'B91 2BD',
          countryId: 'GB',
        },
        additionalContactDetails: [],
        workPhone: '01234 567890',
        email: 'john@reapit.com',
        metadata: null,
        _eTag: '"0A5EB9C9D1B1C156BA189E64FCABE8F9"',
        extrasField: {},
        _links: {
          self: {
            href: '/offices/LEA',
          },
          negotiators: {
            href: '/negotiators/?officeId=LEA',
          },
        },
        _embedded: null,
      },
    ],
    source: {
      id: 'SRC157',
      created: '2022-08-02T11:38:13Z',
      modified: '2022-08-02T11:38:13Z',
      name: 'Propertyfinder WhatsApp',
      type: 'source',
      officeIds: [],
      departmentIds: [],
      _eTag: '"A14777181529994196E3CDA0E05335ED"',
      _links: {
        self: {
          href: '/sources/SRC157',
        },
      },
      _embedded: null,
    },
  },
}
